version: '3.7'

services:

  web:
    build: ./app
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000 
    ports:
      - "8000:8000"
  
  nginx:
    build: ./nginx
    ports: 
      - 1300:80
    depends_on: 
      - web
